services:
  - name: mood-detection-app
    type: web
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8501
    region: oregon
    healthCheckPath: /